# - This is the build pipeline to build and push the automated test docker image to Dockerhub 

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build and Push image
  jobs:  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
       - task: Docker@2
         inputs:
           containerRegistry: '$(ServiceConnectionName)'
           repository: '$(DockerhubRepoName)'
           tags: latest
           command: 'buildAndPush'
           Dockerfile: '**/Dockerfile'
           
       - task: CopyFiles@2
         inputs:
           Contents: 'docker-compose.yml'	
           TargetFolder: '$(Build.ArtifactStagingDirectory)'
           
       - task: PublishBuildArtifacts@1
         inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'drop'
           publishLocation: 'Container'